---
abstract: 'Utility to generate a random dir tree with random files.'
author:
  - 'John Gravatt <john@gravatt.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-RandomGenerator
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  File::Path: 0
  File::Temp: 0
  Modern::Perl: 0
  Moose: 0
  Smart::Args: 0
  namespace::autoclean: 0
version: 0.03
